### PR TITLE
Removed Intercom binary and dSYMs

### PR DESCRIPTION
**Pull request by Br1an-Boyle**

### CODE REVIEW

**Review by KarthikMS — APPROVED** [review]

**Comment by mikklfr** [comment]
👋 This breaked our https://pub.dev/packages/intercom_flutter integration

**Comment by Br1an-Boyle** [comment]
Hi @mikklfr 
How are you integrating intercom into your Flutter app?

**Comment by mikklfr** [comment]
Thanks for your quick response 👍

We are only using the "flutter" way of adding a dependency so things are a bit hidden from the flutter dev perspective.
Under the hood in iOS, the package seems to depend on that .h file and I think that the version fetched by this plugin is not locked correctly, so latest code seems to be pulled from cocoapods leading to the missing .h compilation unit.

Here is the code that seems to fail in the flutter wrapper
https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/ios/Classes/IntercomFlutterPlugin.m

**Comment by Br1an-Boyle** [comment]
@mikklfr should be fixed now.

**Comment by matiasfic** [comment]
This also breaks Capacitor community plugin:

`error: no such module 'Intercom'`

**Comment by Br1an-Boyle** [comment]
@matiasfic Working on a fix to address this now.
Will post here once the issue has been resolved.

**Comment by simplenotezy** [comment]
> Thanks for your quick response 👍
> 
> We are only using the "flutter" way of adding a dependency so things are a bit hidden from the flutter dev perspective. Under the hood in iOS, the package seems to depend on that .h file and I think that the version fetched by this plugin is not locked correctly, so latest code seems to be pulled from cocoapods leading to the missing .h compilation unit.
> 
> Here is the code that seems to fail in the flutter wrapper https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/ios/Classes/IntercomFlutterPlugin.m

Did you find a workaround to revert? I believe, as you said, the previous version is not locked correctly, so it keeps fetching the new faulty version.

**Comment by mikklfr** [comment]
Working fine now, thanks 👍

**Pull request merged**
