### PR TITLE
Revert "Removed Intercom binary and dSYMs"

### PR DESCRIPTION
**Pull request by Br1an-Boyle**
Reverts intercom/intercom-ios#413

### CODE REVIEW

**Review by KarthikMS — APPROVED** [review]

**Comment by stigi** [comment]
Hi @Br1an-Boyle,

Thanks for the quick revert. It seems though like the framework and dSyms are gone from all old tags (ex the one [we're at](https://github.com/intercom/intercom-ios/tree/12.4.3)). Did you rewrite the repo history?

**Comment by FelixHerrmann** [comment]
> Hi @Br1an-Boyle,
> 
> 
> 
> Thanks for the quick revert. It seems though like the framework and dSyms are gone from all old tags (ex the one [we're at](https://github.com/intercom/intercom-ios/tree/12.4.3)). Did you rewrite the repo history?

Pretty sure they did, the repo size is now much smaller: https://api.github.com/repos/intercom/intercom-ios. From an SPM perspective this is good because it was ~2GB which is basically unusable. Imo those dSYMs should be attached to the GH release like the framework is!

**Comment by FelixHerrmann** [comment]
> Hi @Br1an-Boyle,
> 
> 
> 
> Thanks for the quick revert. It seems though like the framework and dSyms are gone from all old tags (ex the one [we're at](https://github.com/intercom/intercom-ios/tree/12.4.3)). Did you rewrite the repo history?

Pretty sure they did, the repo size is now much smaller: https://api.github.com/repos/intercom/intercom-ios. From an SPM perspective this is good because it was ~2GB which is basically unusable. Imo those dSYMs should be attached to the GH release like the framework is!

**Comment by stigi** [comment]
@Br1an-Boyle This must be causing some stress for you and I'm sorry to see that. Thanks for fixing it for all of us 🙌

**Comment by dylmye** [comment]
Thank you for creating this fix! Is there a timeline for this landing in a release?

**Comment by Br1an-Boyle** [comment]
@dylmye yes this is related.
Currently working on a fix for this. Will post an update here once it has been resolved.

**Comment by dylmye** [comment]
Thank you and your team very much <3

**Comment by Br1an-Boyle** [comment]
This issue is now fixed.
Thanks for everyone who reported it.

**Comment by mikklfr** [comment]
Working fine now, thanks 👍

**Pull request merged**
