### PR TITLE
Added SPM support

### PR DESCRIPTION
**Pull request by tony-osibov**

### CODE REVIEW

**Comment by shaps80** [comment]
🤞this goes in soon :)

**Comment by bboyle18** [comment]
Thanks for your PR @tony-osibov 👍 
We're going to be adding support for Swift Package Manager shortly.
We'll have to test this internally first and then deploy a new release, update docs etc. so we won't be able to 👍  this PR as this will all have to be done internally.
However, we will be adding it very shortly, so please keep an eye out for a new release.

Thanks again for this contribution, the team here at Intercom really appreciate it 😄

**Comment by tony-osibov** [comment]
@bboyle18 Thanks for the update! Completely understand you have your own internal process/protocols for code change. I would like to add that I have been testing my fork with the SPM updates for a bit now and so far so good. We have done one release to the App Store and so far no issues 🤞🤞🤞

**Comment by bboyle18** [comment]
Thanks @tony-osibov 
Hoping we'll have this supported soon 🤞

**Comment by bboyle18** [comment]
@tony-osibov @shaps80 
https://github.com/intercom/intercom-ios/releases/tag/9.1.0
SPM is now supported.

**Comment by shaps80** [comment]
Amazing! Thank you :)

**Comment by bboyle18** [comment]
@shaps80 The initial fetching of the framework is a little slow on the first integration, but should be fine once its cached.
Working on reducing the size of the repo to fix this.

**Comment by shaps80** [comment]
I noticed that. Thanks for clarifying.

**Comment by shimazu2** [comment]
@shaps80 Hi, I have noticed slow fetching as well. 
It might be connected to the huge size of .git/objects/pack (~1.3 GB), maybe there is some cleanup you can do?
Running the following command: `git verify-pack -v .git/objects/pack/*.idx | sort -k 3 -n | tail -5`
Reveals the following blobs:
```
4dad63aabc6c3974881de4010964d779bc4765e2 blob   47986972 19913255 250394801
e8197d1e9b9bfba18173057b01b93f62449ca328 blob   47986972 19908608 391641354
6d071afcdc8f772fd647972ef39c8aa275c55f20 blob   56700176 22825454 179810868
f54b8b461567a9102f7cdd08b6e0a2ff67c121c2 blob   56941384 22264578 217631581
c2859a992c4b22e54a6dc9b1ea61c4922cb41545 blob   81424064 37013397 1024071846
```

**Comment by FelixHerrmann** [comment]
Any updates? GitHub API says 1304543kb for size.

**Pull request closed without merging**
